version: '3.9'

services:
  rust_server:
    build: .
    container_name: rust_server
    ports:
      - "5000:5000"
    volumes:
      - ./graficas:/app/graficas

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data: