services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - mi-red
  json-data:
    build:
      context: ./graficas
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /home/roberto/Documentos/sopes1/SOPES1_1S2025/PROYECTO1/rust_services/graficas:/app
    networks:
      - mi-red
networks:
  mi-red:
    driver: bridge