apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: weather-tweets
spec:
  kafka:
    version: 3.8.0  # <--- CORREGIDO aquí
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
