apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: weather-tweets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: producer
          image: rmiguel12/kafka-producer:3.0
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "my-cluster-kafka-bootstrap.weather-tweets:9092"
            - name: KAFKA_TOPIC
              value: "weather-topic"  # Match the topic in your Go code