apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  namespace: tweets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: consumer
        image: rmiguel12/kafka-consumer:19.0
        env:
        - name: REDIS_HOST
          value: "redis-service:6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
